// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function roleToString(role) {
  switch (role) {
    case 0 : 
        return "harvester";
    case 1 : 
        return "upgrader";
    case 2 : 
        return "builder";
    
  }
}

exports.roleToString = roleToString;
/* No side effect */
