// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function roleToString(role) {
  if (role !== 0) {
    return "upgrader";
  } else {
    return "harvester";
  }
}

exports.roleToString = roleToString;
/* No side effect */
