// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


var creepsArray = (Object.keys(Game.creeps));

var spawnsArray = (Object.keys(Game.spawns));

exports.creepsArray = creepsArray;
exports.spawnsArray = spawnsArray;
/* creepsArray Not a pure module */
