// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function toNumResult(sc) {
  switch (sc) {
    case 0 : 
        return 0;
    case 1 : 
        return -1;
    case 2 : 
        return -2;
    case 3 : 
        return -3;
    case 4 : 
        return -4;
    case 5 : 
        return -5;
    case 7 : 
        return -7;
    case 8 : 
        return -8;
    case 9 : 
        return -9;
    case 10 : 
        return -10;
    case 11 : 
        return -11;
    case 12 : 
        return -12;
    case 6 : 
    case 13 : 
        return -6;
    case 14 : 
        return -14;
    case 15 : 
        return -15;
    
  }
}

function toNumFilter(sc) {
  switch (sc) {
    case 0 : 
        return 1;
    case 1 : 
        return 3;
    case 2 : 
        return 5;
    case 3 : 
        return 7;
    case 4 : 
        return 10;
    case 5 : 
        return 101;
    case 6 : 
        return 102;
    case 7 : 
        return 103;
    case 8 : 
        return 104;
    case 9 : 
        return 105;
    case 10 : 
    case 11 : 
        return 106;
    case 12 : 
        return 107;
    case 13 : 
        return 108;
    case 14 : 
        return 109;
    case 15 : 
        return 110;
    case 16 : 
        return 111;
    case 17 : 
        return 112;
    case 18 : 
        return 113;
    case 19 : 
        return 114;
    case 20 : 
        return 115;
    case 21 : 
        return 116;
    
  }
}

exports.toNumResult = toNumResult;
exports.toNumFilter = toNumFilter;
/* No side effect */
