// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var BaseTypes  = require("./baseTypes.js");
var Supplement = require("./supplemental");

function setMemoryField(creepName, memory) {
  if (memory.tag) {
    Supplement.defineMemoryHelper(creepName, "role", BaseTypes.roleToString(memory[0]));
    return /* () */0;
  } else {
    Supplement.defineMemoryHelper(creepName, "working", memory[0] !== 0 ? "true" : "false");
    return /* () */0;
  }
}

exports.setMemoryField = setMemoryField;
/* ./supplemental Not a pure module */
