// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var BaseTypes       = require("./baseTypes.js");
var Supplement      = require("./supplemental");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var NotRoleString = Caml_exceptions.create("Creep.NotRoleString");

function setMemoryField(creep, memory) {
  switch (memory.tag | 0) {
    case 0 : 
        Supplement.defineMemoryHelper(creep, "working", memory[0] !== 0 ? "true" : "false");
        return /* () */0;
    case 1 : 
        Supplement.defineMemoryHelper(creep, "role", BaseTypes.roleToString(memory[0]));
        return /* () */0;
    case 2 : 
        Supplement.defineMemoryHelper(creep, "mining", memory[0] !== 0 ? "true" : "false");
        return /* () */0;
    
  }
}

function getRole(creep) {
  var x = creep.memory.role;
  switch (x) {
    case "harvester" : 
        return /* Harvester */0;
    case "upgrader" : 
        return /* Upgrader */1;
    default:
      Game("ERROR: NO ROLE");
      return /* Harvester */0;
  }
}

exports.NotRoleString  = NotRoleString;
exports.setMemoryField = setMemoryField;
exports.getRole        = getRole;
/* ./supplemental Not a pure module */
