// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var $$Array    = require("bs-platform/lib/js/array.js");
var BaseTypes  = require("./baseTypes.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Supplement = require("./supplemental");

function arrayFilter(filter, array) {
  var list = $$Array.to_list(array);
  return $$Array.of_list(List.filter(filter)(list));
}

function arraySumRecursive(numArray, _currentSum, _currentIndex) {
  while(true) {
    var currentIndex = _currentIndex;
    var currentSum = _currentSum;
    if (numArray.length === currentIndex) {
      return currentSum;
    } else {
      _currentIndex = currentIndex + 1 | 0;
      _currentSum = currentSum + Caml_array.caml_array_get(numArray, currentIndex) | 0;
      continue ;
      
    }
  };
}

function arraySum(numArray) {
  return arraySumRecursive(numArray, 0, 0);
}

function setMemoryField(creepName, memory) {
  if (memory.tag) {
    Supplement.defineMemoryHelper(creepName, "role", BaseTypes.roleToString(memory[0]));
    return /* () */0;
  } else {
    Supplement.defineMemoryHelper(creepName, "working", memory[0] !== 0 ? "true" : "false");
    return /* () */0;
  }
}

exports.arrayFilter       = arrayFilter;
exports.arraySumRecursive = arraySumRecursive;
exports.arraySum          = arraySum;
exports.setMemoryField    = setMemoryField;
/* ./supplemental Not a pure module */
