// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function run() {
  console.log("Deployment succeeded to Screeps Server");
  console.log("Hopefully this will successfully build");
  return /* () */0;
}

exports.run = run;
/* No side effect */
