// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Game          = require("Game");
var Caml_array    = require("bs-platform/lib/js/caml_array.js");
var Roleharvester = require("./roleharvester.js");

function run() {
  console.log("Deployment succeeded to Screeps Server");
  console.log("Hopefully this will successfully build");
  return /* () */0;
}

for(var i = 1; i <= 10; ++i){
  Roleharvester.run(Caml_array.caml_array_get(Game.creeps, i));
}

var creeps = /* () */0;

exports.run    = run;
exports.creeps = creeps;
/*  Not a pure module */
