// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var creeps = (Object.keys(Game.creeps));

var spawns = (Object.keys(Game.spawns));

function iterateCreeps() {
  var x = creeps.length;
  if (x !== 0) {
    console.log("There are " + (Pervasives.string_of_int(x) + " creeps currently"));
    for(var i = 0 ,i_finish = creeps.length - 1 | 0; i <= i_finish; ++i){
      console.log("One is named " + Caml_array.caml_array_get(creeps, i));
    }
    return /* () */0;
  } else {
    console.log("There are no creeps to iterate over");
    return /* () */0;
  }
}

function iterateSpawns() {
  var x = spawns.length;
  if (x !== 0) {
    console.log("There are " + (Pervasives.string_of_int(x) + " spawns currently"));
    for(var i = 0 ,i_finish = spawns.length - 1 | 0; i <= i_finish; ++i){
      console.log("One is named " + Caml_array.caml_array_get(spawns, i));
    }
    return /* () */0;
  } else {
    console.log("There are no spawns to iterate over (should be untrue)");
    return /* () */0;
  }
}

function run() {
  var time = (Date.now());
  console.log(time);
  iterateSpawns(/* () */0);
  return iterateCreeps(/* () */0);
}

var runEachTick = run(/* () */0);

var creepsArray = creeps;

var spawnsArray = spawns;

exports.creeps        = creeps;
exports.creepsArray   = creepsArray;
exports.spawns        = spawns;
exports.spawnsArray   = spawnsArray;
exports.iterateCreeps = iterateCreeps;
exports.iterateSpawns = iterateSpawns;
exports.run           = run;
exports.runEachTick   = runEachTick;
/* creeps Not a pure module */
