// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function runCreep() {
  console.log("Upgrades cost oil in Scythe");
  return /* () */0;
}

exports.runCreep = runCreep;
/* No side effect */
