// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var ConstantConv = require("./constantConv.js");

function get_struct_type(r) {
  return ConstantConv.fromStringStructure(r.structureType);
}

function find(r, f) {
  return r.find(ConstantConv.toNumFilter(f));
}

exports.get_struct_type = get_struct_type;
exports.find            = find;
/* No side effect */
