// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var $$Array      = require("bs-platform/lib/js/array.js");
var BaseTypes    = require("./baseTypes.js");
var ConstantConv = require("./constantConv.js");
var Supplement   = require("./supplemental");

function spawnCreepWithMemory(spawn, body, mfa) {
  var $js;
  $js = mfa.tag ? /* array */[
      "role",
      BaseTypes.roleToString(mfa[0])
    ] : /* array */[
      "working",
      mfa[0] ? "true" : "false"
    ];
  return Supplement.spawnCreepWithMemoryHelper(spawn, $$Array.map(ConstantConv.bodyPartToString, body), $js);
}

exports.spawnCreepWithMemory = spawnCreepWithMemory;
/* ./supplemental Not a pure module */
