// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Curry           = require("bs-platform/lib/js/curry.js");
var ConstantConv    = require("./constantConv.js");
var Supplement      = require("./supplemental");
var HelperFunctions = require("./helperFunctions.js");

function spawnCreepWithRole(spawn, body, r) {
  return Supplement.spawnCreepWithMemoryHelper(spawn, Curry._2(HelperFunctions.$$Array[/* map */12], ConstantConv.bodyPartToString, body), /* array */[
              "role",
              r !== 0 ? "upgrader" : "harvester"
            ]);
}

exports.spawnCreepWithRole = spawnCreepWithRole;
/* ./supplemental Not a pure module */
