// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Curry           = require("bs-platform/lib/js/curry.js");
var ConstantConv    = require("./constantConv.js");
var Supplement      = require("./supplemental");
var HelperFunctions = require("./helperFunctions.js");

function spawnCreepWithRole(spawn, body, r) {
  var $js;
  switch (r) {
    case 0 : 
        $js = "harvester";
        break;
    case 1 : 
        $js = "upgrader";
        break;
    case 2 : 
        $js = "builder";
        break;
    
  }
  return Supplement.spawnCreepWithMemoryHelper(spawn, Curry._2(HelperFunctions.$$Array[/* map */12], ConstantConv.bodyPartToString, body), /* array */[
              "role",
              $js
            ]);
}

exports.spawnCreepWithRole = spawnCreepWithRole;
/* ./supplemental Not a pure module */
