// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function runTower() {
  console.log("I AM A TOWER");
  return /* () */0;
}

exports.runTower = runTower;
/* No side effect */
